version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_DATABASE: MyApp
    volumes:
      - mongo_data:/data/db


  db:
    image: postgres:15
    container_name: book_store_sql_container
    restart: always
    environment:
      POSTGRES_USER: waseem
      POSTGRES_PASSWORD: waseem123
      POSTGRES_DB: book_store_db
    ports:
      - "5432:5432"

volumes:
  mongo_data:
